[package]
name = "dotfiles"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sys-info = "0.9.1"
git2 = "0.13.25"
home = "0.5.3"
spinners = "2.0.0"
rpassword = "5.0.1"