[bootstrap.brew.taps]
"homeport/tap" = "https://github.com/homeport/homebrew-tap.git"
"jewlexx/tap" = "https://github.com/jewlexx/homebrew-tap.git"
"nohajc/anylinuxfs" = "https://github.com/nohajc/homebrew-anylinuxfs.git"

[bootstrap.packages]
"brew:bacon" = "latest"
"brew:bat" = "latest"
"brew:btop" = "latest"
"brew:clipboard" = "latest"
"brew:coreutils" = "latest"
"brew:cowsay" = "latest"
"brew:dust" = "latest"
"brew:eza" = "latest"
"brew:fastfetch" = "latest"
"brew:ffmpeg-full" = "latest"
"brew:fzf" = "latest"
"brew:git-delta" = "latest"
"brew:git-lfs" = "latest"
"brew:gnupg" = "latest"
"brew:hyperfine" = "latest"
"brew:imagemagick" = "latest"
"brew:jewlexx/tap/dirkill" = "latest"
"brew:jewlexx/tap/rmx" = "latest"
"brew:jpeg-turbo" = "latest"
"brew:lld" = "latest"
"brew:llvm" = "latest"
"brew:lzo" = "latest"
"brew:mise" = "latest"
"brew:neovim" = "latest"
"brew:pcre2" = "latest"
"brew:pinentry-mac" = "latest"
"brew:pipx" = "latest"
"brew:pixman" = "latest"
"brew:pkgconf" = "latest"
"brew:ripgrep" = "latest"
"brew:rustup" = "latest"
"brew:sdl2-compat" = "latest"
"brew:sdl3" = "latest"
"brew:starship" = "latest"
"brew:tokei" = "latest"
"brew:uutils-coreutils" = "latest"
"brew:xorgproto" = "latest"
"brew:xvid" = "latest"
"brew:xz" = "latest"
"brew:yt-dlp" = "latest"
"brew:zoxide" = "latest"
"brew:zstd" = "latest"
