[gpg]
program = "C:\\Program Files\\GnuPG\\bin\\gpg.EXE"

[credential "helperselector"]
selected = manager

[include]
path = "~/.dotfiles/configs/git.properties"

[credential]
helper = manager

[core]
	autocrlf = true
	fscache = true
	symlinks = true
	sshCommand = 'C:\\Windows\\System32\\OpenSSH\\ssh.exe'

[credential]
credentialStore = wincredman
[diff "lockb"]
	textconv = bun
	binary = true
