[package]
name = "setup"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
git2 = "0.14.3"
lazy_static = "1.4.0"

[target.x86_64-pc-windows-msvc.dependencies]
winapi = "0.3.9"
