[package]
name = "setup"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
directories = "4.0.1"
git2 = "0.14.2"
threadpool = "1.8.1"
which = "4.2.5"
colored = "2.0.0"
spinners = "3.1.0"

